// Generated by CoffeeScript 1.7.1
(function() {
  var assert, poker;

  assert = require("assert-plus");

  poker = require("poker");

  describe("the app", function() {
    return it("should rank the given example hands", function() {
      var input, output;
      input = "Kc 9s Ks Kd 9d 3c 6d\n9c Ah Ks Kd 9d 3c 6d\nAc Qc Ks Kd 9d 3c\n9h 5s\n4d 2d Ks Kd 9d 3c 6d\n7s Ts Ks Kd 9d";
      output = "Kc 9s Ks Kd 9d 3c 6d Full House (winner)\n9c Ah Ks Kd 9d 3c 6d Two Pair\nAc Qc Ks Kd 9d 3c Pair\n9h 5s High Card\n4d 2d Ks Kd 9d 3c 6d Flush\n7s Ts Ks Kd 9d Pair";
      return assert.equal(poker.rank(input), output);
    });
  });

}).call(this);
